name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3.3.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1.5.1
        with:
          deno-version: v1.46.3

      - name: Check
        run: deno task check

